### ISSUE TITLE
Preparing the package

### ISSUE THREAD

**Issue by gsilvapt** [gsilvapt/gini-index#1]
Running the tools:

**Validator:** http://data.okfn.org/tools/validate?url=https%3A%2F%2Fgithub.com%2Fgsilvapt%2Fgini-index

**Viewer:** http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fgsilvapt%2Fgini-index

**Comment by zelima** [comment]
@gsilvapt Think we can close this issue.

**Comment by gsilvapt** [comment]
Absolutely.

> The data has landed here: http://data.okfn.org/data/core/gini-index
> It would be great if someone tweeted about this.
